version: "3.9"
services:
  tika:
    build:
      context: ./tika
    ports:
      - "9998:9998"
    deploy:
      restart_policy:
        condition: always
  mapachon:
    build:
      context: .
    command: /mapachon -tika http://tika:9998 -out /out/dump.db /dump
    depends_on:
      - tika
    volumes:
      - ${DUMP_INPUT:?missing required DUMP_INPUT}:/dump
      - ${DUMP_OUTPUT:-.}:/out
