// Code generated by entc, DO NOT EDIT.

package artifact

const (
	// Label holds the string label denoting the artifact type in the database.
	Label = "artifact"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFilePath holds the string denoting the file_path field in the database.
	FieldFilePath = "file_path"
	// FieldArchivePath holds the string denoting the archive_path field in the database.
	FieldArchivePath = "archive_path"
	// FieldFileType holds the string denoting the file_type field in the database.
	FieldFileType = "file_type"
	// FieldParsedContent holds the string denoting the parsed_content field in the database.
	FieldParsedContent = "parsed_content"
	// Table holds the table name of the artifact in the database.
	Table = "artifacts"
)

// Columns holds all SQL columns for artifact fields.
var Columns = []string{
	FieldID,
	FieldFilePath,
	FieldArchivePath,
	FieldFileType,
	FieldParsedContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
